const database = [
  {
    brand: 'Xiomi',
    model: 'Mi 6',
    so: 'Android',
    screenSize: 5.15,
    frequency: 2.45,
    cores: 4,
    ram: 6,
    storage: 128,
    dualSim: true,
    price: 2100
  },
  {
    brand: 'HTC',
    model: 'One X10',
    so: 'Android',
    screenSize: 5.5,
    frequency: 1.8,
    cores: 4,
    ram: 3,
    storage: 32,
    dualSim: true,
    price: 2499
  },
  {
    brand: 'Huawei',
    model: 'Hono 8 Pro',
    so: 'Android',
    screenSize: 5.7,
    frequency: 2.4,
    cores: 4,
    ram: 4,
    storage: 64,
    dualSim: true,
    price: 1900
  },
  {
    brand: 'Quantum',
    model: 'MUV Up',
    so: 'Android',
    screenSize: 5.5,
    frequency: 1.3,
    cores: 8,
    ram: 3,
    storage: 32,
    dualSim: true,
    price: 999
  },
  {
    brand: 'Samsung',
    model: 'Galaxy S8',
    so: 'Android',
    screenSize: 5.8,
    frequency: 2.3,
    cores: 4,
    ram: 4,
    storage: 64,
    dualSim: false,
    price: 3519
  },
  {
    brand: 'Sony',
    model: 'Xperia L1',
    so: 'Android',
    screenSize: 5.5,
    frequency: 1.4,
    cores: 4,
    ram: 2,
    storage: 16,
    dualSim: true,
    price: 2229
  },
  {
    brand: 'LG',
    model: 'G6',
    so: 'Android',
    screenSize: 5.7,
    frequency: 2.35,
    cores: 2,
    ram: 4,
    storage: 32,
    dualSim: false,
    price: 2399
  },
  {
    brand: 'Motorola',
    model: 'Moto G5',
    so: 'Android',
    screenSize: 5,
    frequency: 1.4,
    cores: 4,
    ram: 4,
    storage: 32,
    dualSim: true,
    price: 1349
  },
  {
    brand: 'Asus',
    model: 'Zenfone AR',
    so: 'Android',
    screenSize: 5.7,
    frequency: 2.35,
    cores: 2,
    ram: 8,
    storage: 256,
    dualSim: true,
    price: 2249
  },
  {
    brand: 'Lenovo',
    model: 'Zuk Edge',
    so: 'Android',
    screenSize: 5.5,
    frequency: 2.35,
    cores: 2,
    ram: 6,
    storage: 64,
    dualSim: true,
    price: 2349
  },
  {
    brand: 'Apple',
    model: 'Iphone 7 Plus',
    so: 'IOS',
    screenSize: 5.5,
    frequency: 2.2,
    cores: 4,
    ram: 3,
    storage: 256,
    dualSim: false,
    price: 3059
  }
];