const database = [{
        id: 1,
        brand: 'Xiaomi',
        model: 'Mi 6',
        so: 'Android',
        screenSize: 5.15,
        ram: 6,
        storage: 128,
        dualSim: true,
        price: 2100.0,
    },
    {
        id: 2,
        brand: 'HTC',
        model: 'One X10',
        so: 'Android',
        screenSize: 5.5,
        ram: 3,
        storage: 32,
        dualSim: true,
        price: 2499.0
    },
    {
        id: 3,
        brand: 'Huawei',
        model: 'Hono 8 Pro',
        so: 'Android',
        screenSize: 5.7,
        ram: 4,
        storage: 64,
        dualSim: true,
        price: 1900.0
    },
    {
        id: 4,
        brand: 'Quantum',
        model: 'MUV Up',
        so: 'Android',
        screenSize: 5.5,
        ram: 3,
        storage: 32,
        dualSim: true,
        price: 999.0
    },
    {
        id: 5,
        brand: 'Samsung',
        model: 'Galaxy S8',
        so: 'Android',
        screenSize: 5.8,
        ram: 4,
        storage: 64,
        dualSim: false,
        price: 3519.0
    },
    {
        id: 6,
        brand: 'Sony',
        model: 'Xperia L1',
        so: 'Android',
        screenSize: 5.5,
        ram: 2,
        storage: 16,
        dualSim: true,
        price: 2229.0
    },
    {
        id: 7,
        brand: 'LG',
        model: 'G6',
        so: 'Android',
        screenSize: 5.7,
        ram: 4,
        storage: 32,
        dualSim: false,
        price: 2399.0
    },
    {
        id: 8,
        brand: 'Motorola',
        model: 'Moto G5',
        so: 'Android',
        screenSize: 5.0,
        ram: 4,
        storage: 32,
        dualSim: true,
        price: 1349.0
    },
    {
        id: 9,
        brand: 'Asus',
        model: 'Zenfone AR',
        so: 'Android',
        screenSize: 5.7,
        ram: 8,
        storage: 256,
        dualSim: true,
        price: 2249.0
    },
    {
        id: 10,
        brand: 'Lenovo',
        model: 'Zuk Edge',
        so: 'Android',
        screenSize: 5.5,
        ram: 6,
        storage: 64,
        dualSim: true,
        price: 2349.0
    },
    {
        id: 11,
        brand: 'Apple',
        model: 'Iphone 7 Plus',
        so: 'iOS',
        screenSize: 5.5,
        ram: 3,
        storage: 256,
        dualSim: false,
        price: 3059.0
    }
];